kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-altinn-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-altinn-acl/amt-altinn-acl:{{version}}
  port: 8080
  ingresses:
    - https://amt-altinn-acl.dev.intern.nav.no
    - https://amt-altinn-acl.intern.dev.nav.no

  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  env:
    - name: ALTINN_KOORDINATOR_SERVICE_CODE
      value: "5858"
    - name: ALTINN_VEILEDER_SERVICE_CODE
      value: "5859"
    - name: ALTINN_URL
      value: https://tt02.altinn.no
    - name: MASKINPORTEN_URL
      value: https://ver2.maskinporten.no
  envFrom:
    - secret: altinn-api-key
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
  gcp:
    sqlInstances:
      - name: amt-altinn-acl
        type: POSTGRES_14
        tier: db-g1-small
        databases:
          - name: amt-altinn-acl
            envVarPrefix: DB
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/reportees"
        - name: "altinn:serviceowner/rolesandrights"
