kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-altinn-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-altinn-acl.intern.dev.nav.no

  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 512Mi
  leaderElection: true
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=70.0"
    - name: ALTINN3_URL
      value: https://platform.tt02.altinn.no
    - name: MASKINPORTEN_URL
      value: https://ver2.maskinporten.no
  envFrom:
    - secret: amt-altinn-acl-unleash-api-token
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-arrangor
    outbound:
      external:
        - host: platform.tt02.altinn.no
        - host: amt-unleash-api.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - name: amt-altinn-acl-2
        type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: amt-altinn-acl
            envVarPrefix: DB
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki