kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-altinn-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-altinn-acl/amt-altinn-acl:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - name: amt-altinn-acl
        type: POSTGRES_14
        tier: db-g1-small
        databases:
          - name: amt-altinn-acl
            envVarPrefix: DB
  env:
    - name: ALTINN_URL
      value: https://www.altinn.no
    - name: MASKINPORTEN_URL
      value: https://maskinporten.no
  envFrom:
    - secret: altinn-api-key
