kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-altinn-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-altinn-acl.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  startup:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 60
    periodSeconds: 5
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-arrangor
    outbound:
      external:
        - host: platform.altinn.no
        - host: amt-unleash-api.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - name: amt-altinn-acl
        type: POSTGRES_14
        tier: db-g1-small
        databases:
          - name: amt-altinn-acl
            envVarPrefix: DB
  leaderElection: true
  env:
    - name: ALTINN3_URL
      value: https://platform.altinn.no
    - name: MASKINPORTEN_URL
      value: https://maskinporten.no
  envFrom:
    - secret: amt-altinn-acl-unleash-api-token
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
