apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: amt-altinn-acl
  namespace: amt
  labels:
    team: amt
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: amt
  secretName: amt-altinn-acl-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: development