logging:
  config: classpath:logback-local.xml
elector:
  path: dont_look_for_leader
server:
  port: '8089'
altinn3:
  url: http://localhost:9002/altinn
maskinporten:
  scopes: altinn
  token-endpoint: http://localhost:9002/maskinporten/token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/azure
          audiences: amt-altinn
  datasource:
    url: jdbc:postgresql://localhost:5432/amt_altinn_db
    username: myuser
    password: mypassword
