spring:
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 25s
  datasource:
    url: ${DB_JDBC_URL}
    hikari:
      maximum-pool-size: 3

  http:
    clients:
      connect-timeout: 5s
      read-timeout: 20s
    serviceclient:
      altinn3:
        base-url: ${altinn3.url}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          audiences: ${AZURE_APP_CLIENT_ID}
          authorities-claim-name: roles
          authority-prefix: ROLE_

server:
  shutdown: graceful

management:
  endpoint:
    prometheus:
      access: read_only
    health:
      probes:
        enabled: true
      group:
        liveness:
          include:
            - livenessState
  endpoints:
    web:
      base-path: /internal
      exposure:
        include:
          - prometheus
          - health
  prometheus:
    metrics:
      export:
        enabled: true

altinn3:
  url: ${ALTINN3_URL}

maskinporten:
  scopes: ${MASKINPORTEN_SCOPES}
  client-id: ${MASKINPORTEN_CLIENT_ID}
  issuer: ${MASKINPORTEN_ISSUER}
  token-endpoint: ${MASKINPORTEN_TOKEN_ENDPOINT}
  client-jwk: ${MASKINPORTEN_CLIENT_JWK}
